### ISSUE TITLE
Ship Log last line Overlap/Overflow

### ISSUE THREAD

**Issue by Marco-Zechner** [FirstPersonKSP/RasterPropMonitor#137]
**Describe the bug**

The log that was last added (if the screen is already full) is always outside of the area.
For 1 line log behind the bottom text.
For 2 line log the first line is behind the bottom text and the second is completely outside and not visible

**KSP.log file**
ALL BUG REPORTS MUST INCLUDE A KSP.LOG FILE
[KSP.log](https://github.com/user-attachments/files/16240648/KSP.log)

**To Reproduce**
Steps to reproduce the behaviour:
1. Build a ship with enough parts to fill the ship log.
2. Do an action that produces a ship log.
3. The new Ship log will be behind the bottom text or a part outside the screen.

**Expected behaviour**
- Scrolling through the logs with the up/down buttons.
- The text moves up, removes old logs and shows the new.
(The "new" log DOES move up, but only when another new one is below in the non-readable space)

**Screenshots**
![image](https://github.com/user-attachments/assets/48e6d56d-f05c-49f3-8f59-ae57df92c758)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by JonnyOThan** [comment]
This needs to be fixed in ASET props.

```
				pageTitle = $$$============= Flight Log ==================
				screenWidth = 40
				screenHeight = 18
```

The $$$ there is a line break, which makes sure the page title appears below the top row of button labels.  There's also a bottom row of button labels.  The full display is 20 lines tall, so screenHeight needs to be 17 not 18.
