### ISSUE TITLE
[CKAN] v1.0.1 installation does not overwrite RasterPropMonitor Core files leaving messy installation

### ISSUE THREAD

**Issue by fastdelaspeed** [FirstPersonKSP/RasterPropMonitor#147]
**Describe the bug**
Hello, first off, not sure if this should go here or in the CKAN repo, so my apologies. Please let me know if there's somewhere else to put this issue.

It appears that within CKAN, the latest RPM package conflicts with the RPM Core package. It appears that with v1.0.1, the RPM Core package is no longer needed, but CKAN does not realize that. When updating from RPM v0.31.13.4 to v1.0.1, core DLLs are not overwritten which means that the installed version of RPM is stuck on v0.31.13.4. Dependencies are also still tied to the old RPM Core package, so removal via CKAN isn't possible without also removing all RPM dependent mods.

**KSP.log file**
N/A

**To Reproduce**
1. Attempt to upgrade RPM via CKAN
2. CKAN reports successfully installed updates v0.31.13.4 > v1.0.1
3. due to conflict with RPM Core package the RPM DLLs provided by v1.0.1 are not replaced

This behaviour can be verified by checking the file modification date on RasterPropMonitor.dll or by launching KSP with deferred rendering and seeing the black borders around the text, confirming that the old version is still installed.

**Expected behavior**
Within CKAN, RPM Core is replaced by RPM v1.0.1 and dependents are satisfied.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Manually extracting the zip to overwrite the files fixes the issue.

**Comment by HebaruSan** [comment]
Probably fixed by KSP-CKAN/NetKAN#10217 and https://github.com/KSP-CKAN/CKAN-meta/commit/60141bfd22e57216f90316a1208f4c768ab6b0cf

**Comment by JonnyOThan** [comment]
seems like the same issue as #146 in an indirect way.
